application: villagegamedev
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /client/assets
  static_dir: assets

- url: /purchases
  script: village.braindemo.create_purchase

- url: /client/braindemo.html
  static_files: client/braindemo.html
  upload: client/braindemo.html

- url: /client/$
  static_files: client/index_deploy.html
  upload: client/index_deploy.html

- url: /client/dev$
  static_files: client/index.html
  upload: client/index.html

- url: /client/
  static_dir: client

- url: /ige
  static_dir: ige

- url: /api/.*
  script: village.api.root

- url: /.*
  script: village.main.root

libraries:
- name: pycrypto
  version: latest

skip_files:
- .venv/
- libs/Crypto/
- (.*).pyc$
- /.git/
- (.*).pack$
- \(
- ^ige/
